{
 "title": "freqtrade",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job name",
    "query": {
     "query": "label_values(freqtrade_build_info, job)"
    }
   },
   {
    "name": "strategy",
    "label": "Strategy name",
    "query": {
     "query": "label_values(freqtrade_build_info{job=~\"$job\"}, strategy)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Profit",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (freqtrade_pair_performance_profit_abs{})",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum (freqtrade_pair_performance_profit_abs{})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg profit per pair freqtrade3",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freqtrade_pair_performance_profit_pct{job=\"freqtrade3\"}",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Avg profit",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job)(freqtrade_pair_performance_profit_pct{}) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg profit per pair freqtrade1",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freqtrade_pair_performance_profit_pct{job=\"freqtrade1\"}",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Won trades",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (freqtrade_trade_winning{}) / sum by (job) (freqtrade_trade_total{}) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg trade duration",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job)(freqtrade_trade_avg_duration_seconds{}/60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Profit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(job)(freqtrade_pair_performance_profit_abs{})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Balance Fiat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "avg by(job)(freqtrade_crypto_balance{})",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Trades",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (freqtrade_trade_total{})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open Trades",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (freqtrade_trade_open_current)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open trades over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "freqtrade_trade_open_current", "legendFormat": "{{job}}" }
   ]
  }
 ]
}